[custom]
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=全球直连,https://raw.githubusercontent.com/timwa0669/ruleset/master/ruleset/CaptivePortal.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
#ruleset=广告拦截,https://raw.githubusercontent.com/timwa0669/ruleset/master/ruleset/CustomADReject.list
ruleset=广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=隐私防护,https://raw.githubusercontent.com/timwa0669/ruleset/master/ruleset/CustomPrivacyReject.list
ruleset=漏网之鱼,[]FINAL

custom_proxy_group=默认`select`[]全球直连`[]拒绝连接
custom_proxy_group=全球直连`select`[]DIRECT`[]REJECT
custom_proxy_group=拒绝连接`select`[]REJECT`[]DIRECT
custom_proxy_group=广告拦截`select`[]拒绝连接`[]全球直连
custom_proxy_group=应用净化`select`[]拒绝连接`[]全球直连
custom_proxy_group=隐私防护`select`[]拒绝连接`[]全球直连
custom_proxy_group=漏网之鱼`select`[]默认`[]全球直连

enable_rule_generator=true
overwrite_original_rules=true